import {createSign} from 'node:crypto';
import {db,rpc} from './db.js';
import {commissions,notification} from './domain.js';
export async function telegram(chat,text){if(!process.env.TELEGRAM_BOT_TOKEN)throw new Error('Telegram bot is not configured');const r=await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text}),signal:AbortSignal.timeout(12000)});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.description||'Telegram delivery failed');}
async function googleToken(){if(!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||!process.env.GOOGLE_PRIVATE_KEY)throw new Error('Google Sheets credentials are not configured');const now=Math.floor(Date.now()/1000),enc=o=>Buffer.from(JSON.stringify(o)).toString('base64url');const jwt=enc({alg:'RS256',typ:'JWT'})+'.'+enc({iss:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const sign=createSign('RSA-SHA256');sign.update(jwt);const assertion=jwt+'.'+sign.sign(process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g,'\n'),'base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),signal:AbortSignal.timeout(12000)});const data=await r.json();if(!r.ok)throw new Error('Google service account authentication failed');return data.access_token;}
export function sheetRow(t){const c=t.status==='Approved'?commissions(t.amount_cents,t.final_split):{earned:[0,0,0]};return t.kind==='sale'?[t.reference,t.submitted_at,t.employee,t.customer,t.project,t.description,t.amount_cents/100,...t.proposed_split,...(t.final_split||['','','']),...c.earned.map(x=>x/100),t.status]:[t.reference,t.submitted_at,t.employee,t.description,t.category,t.amount_cents/100,t.proposed_allocation,t.final_allocation||'',t.status];}
const headers={sale:['Reference','Submission time','Salesperson','Customer','Project','Description','Amount EUR','Proposed Richard %','Proposed Anastasia %','Proposed Jean-Claude %','Approved Richard %','Approved Anastasia %','Approved Jean-Claude %','Richard earned EUR','Anastasia earned EUR','Jean-Claude earned EUR','Status'],expense:['Reference','Submission time','Reporter','Description','Category','Amount EUR','Proposed allocation','Final allocation','Status']};
async function sheet(t){if(!process.env.GOOGLE_SHEET_ID)throw new Error('Google spreadsheet is not configured');const token=await googleToken(),tab=t.kind==='sale'?'Sales':'Expenses',end=t.kind==='sale'?'Q':'I';const url=`https://sheets.googleapis.com/v4/spreadsheets/${process.env.GOOGLE_SHEET_ID}/values:batchUpdate`;const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'RAW',data:[{range:`${tab}!A1:${end}1`,values:[headers[t.kind]]},{range:`${tab}!A${t.sheet_row}:${end}${t.sheet_row}`,values:[sheetRow(t)]}]}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Google Sheets update failed (${r.status}); check API enablement, tab names and Editor sharing.`);}
export async function drain(ref){const jobs=await db(`outbox?reference=eq.${encodeURIComponent(ref)}&state=in.(pending,failed,processing)&order=id.asc`);for(const candidate of jobs){const job=await rpc('claim_delivery',{job_id:candidate.id});if(!job)continue;try{if(job.channel==='sheets'){const [latest]=await db(`transactions?reference=eq.${encodeURIComponent(ref)}`);await sheet(latest);}else await telegram(job.payload.recipient_chat,notification(job.payload,job.event));await rpc('finish_delivery',{job_id:job.id,failure:null});}catch(e){await rpc('finish_delivery',{job_id:job.id,failure:e.message});}}}
