export const employees = {svetlana:'Svetlana de Monte Carlo',richard:'Richard Darling',anastasia:'Anastasia Ferrari',jean:'Jean-Claude Bērziņš',kevin:'Kevin von Whatever'};
export const sellers = ['richard','anastasia','jean'];
export function assertRole(role,allowed){if(!allowed.includes(role))throw new Error('This demonstration role cannot perform that action.');}
export function splitCheck(split){if(!Array.isArray(split)||split.length!==3||split.some(x=>typeof x!=='number'||!Number.isFinite(x)||x<0||x>100)||Math.abs(split.reduce((a,b)=>a+b,0)-100)>0.000001)throw new Error('Three commission shares must be between 0 and 100 and total 100%.');return split;}
export function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))throw new Error('Enter a positive euro amount with at most two decimals.');const n=Math.round(Number(value)*100);if(!Number.isSafeInteger(n)||n<=0||n>100000000000)throw new Error('Amount must be greater than zero and at most €1 billion.');return n;}
export function commissions(amount,split){splitCheck(split);const pool=Math.round(amount/10),earned=split.map(p=>Math.round(pool*p/100));const winner=split.indexOf(Math.max(...split));earned[winner]+=pool-earned.reduce((a,b)=>a+b,0);return {pool,earned};}
export function submission(role,input){assertRole(role,input.kind==='sale'?sellers:['kevin']);const reference=String(input.reference||'').trim().toUpperCase();if(!/^[A-Z0-9][A-Z0-9_-]{0,39}$/.test(reference))throw new Error('A unique reference of 1–40 letters, numbers, underscores or hyphens is required.');const description=String(input.description||'').trim();if(!description||description.length>2000)throw new Error('Description is required, maximum 2000 characters.');const result={kind:input.kind,reference,description,amount_cents:cents(input.amount),employee:role};if(input.kind==='sale'){if(!['A','B'].includes(input.project))throw new Error('Select project A or B.');const customer=String(input.customer||'').trim();if(!customer||customer.length>200)throw new Error('Customer is required, maximum 200 characters.');Object.assign(result,{customer,project:input.project,proposed_split:splitCheck(input.split)});}else{if(input.kind!=='expense'||!['Materials','Travel','Other'].includes(input.category)||!['A','B','Overhead'].includes(input.allocation))throw new Error('Select an expense category and allocation.');Object.assign(result,{category:input.category,proposed_allocation:input.allocation});}return result;}
export function dashboard(records){const result={A:{income:0,commissions:0,expenses:0,result:0},B:{income:0,commissions:0,expenses:0,result:0},income:0,commissions:0,expenses:0,overhead:0,awaiting:0,result:0,earned:[0,0,0],pendingSales:0};for(const t of records){if(t.kind==='sale'){if(t.status!=='Approved'){result.pendingSales+=t.amount_cents;continue;}const c=commissions(t.amount_cents,t.final_split);result[t.project].income+=t.amount_cents;result[t.project].commissions+=c.pool;result.income+=t.amount_cents;result.commissions+=c.pool;c.earned.forEach((v,i)=>result.earned[i]+=v);}else{result.expenses+=t.amount_cents;if(t.final_allocation==='Overhead')result.overhead+=t.amount_cents;else if(t.final_allocation)result[t.final_allocation].expenses+=t.amount_cents;else result.awaiting+=t.amount_cents;}}for(const p of ['A','B'])result[p].result=result[p].income-result[p].commissions-result[p].expenses;result.result=result.income-result.commissions-result.expenses;return result;}
export const euro=c=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(c/100);
export function notification(t,event){if(event==='submission')return `${t.reference} recorded. ${euro(t.amount_cents)}. ${t.project||t.proposed_allocation}. Status: ${t.status}.`;if(t.kind==='expense')return `Expense ${t.reference} — allocation ${t.proposed_allocation===t.final_allocation?'confirmed':'changed'}. ${euro(t.amount_cents)}: ${t.description}. Proposed: ${t.proposed_allocation}. Approved: ${t.final_allocation}.`;const c=commissions(t.amount_cents,t.final_split);return `Sale ${t.reference} approved — commission split ${JSON.stringify(t.proposed_split)===JSON.stringify(t.final_split)?'unchanged':'changed'}. Sale ${euro(t.amount_cents)}; total commission ${euro(c.pool)}. `+sellers.map((s,i)=>`${employees[s]}: ${t.proposed_split[i]}% → ${t.final_split[i]}% (${euro(c.earned[i])}).`).join(' ');}
